#!/usr/bin/env zsh

num_attempts=${1:-50}

function print_results () {
    touch "$2"
    len_paths=$3
    atts=${4:-$num_attempts}
    for (( j = 1; j <= $atts; j++ )); do
        for (( i = 0; i < $len_paths; i++ )); do
            (( index = j + i * $atts ))
            echo -n "${(P)${1}[$index]}" >> "$2"
            let "comma_idx = $len_paths - 1"
            if [ $i -ne $comma_idx ]; then
                echo -n "," >> "$2"
            fi
        done
        echo >> "$2"
    done
}

sample_sizes=(`find tests -name "*.in" | sed -e "s/^tests\\/s//" -e "s/-n.*$//" | sort -u`)

rm results/*.out.csv

for sample_size in "${sample_sizes[@]}"; do
    paths=(`find tests -name "s${sample_size}-*.in" | sort`)

    declare -a results_vec=()
    declare -a results_ht=()

    for file in $paths; do
        echo "Testing $file..."
        echo -n "- array"

        ./output/ex-6.out < $file > /dev/null 2> /dev/null
        for (( i = 1; i <= $num_attempts; i++ )); do
            output=(`./output/ex-6.out < $file 2>&1 >/dev/null`)
            results_vec+=(${output[1]})
        done

        echo " [done]"
        echo -n "- hash table"

        ./output/ex-6-ht.out < $file > /dev/null 2> /dev/null
        for (( i = 1; i <= $num_attempts; i++ )); do
            output=(`./output/ex-6-ht.out < $file 2>&1 >/dev/null`)
            results_ht+=(${output[1]})
        done

        echo " [done]"
    done

    echo "Writing files..."

    print_results "results_vec" "results/s${sample_size}.out.csv" ${#paths[@]}
    print_results "results_ht" "results/s${sample_size}-ht.out.csv" ${#paths[@]}

    echo
done
